package com.bi.model.Document;

public enum TokenType {
//	EMR_ACCESS_FOR_UHID,
//	EMR_SHARE_WITH_NON_GMC_DOC,
//	EMR_SHARE_WITH_GMC_DOC,
//	EMR_GM_SHARE_WITH_NON_GMC_DOC,
//	EMR_GM_SHARE_WITH_GMC_DOC,
//	SEND_OTP_FOR_ORDER,
//	GM_SHARE_VITALS,
//	GM_SHARE_DOCUMENT,
//	GM_SHARE_UPLOADED_DOCUMENTS,
//	MEETING_ACCESS_FOR_VIRTUAL_APPT,
}